name: caonalyzer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.3+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  tflite_flutter: ^0.10.1
  camera: ^0.10.5+1
  image: ^4.0.17
  flutter_vision: ^1.1.1
  photo_view: ^0.14.0
  hive: ^2.2.3
  path_provider: ^2.0.15
  path: ^1.8.3
  glob: ^2.1.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  package_info_plus: ^4.0.2
  meta: ^1.9.1
  get_it: ^7.6.0
  fl_chart: ^0.63.0
  collection: ^1.17.1
  isolate_manager: ^3.0.1
  permission_handler: ^10.4.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/labels.txt
    # - ./assets/yolov8n.torchscript.pt
    - assets/yolov8n.tflite
    - assets/svgs/undraw_photograph_re_up3b.svg
